AWSTemplateFormatVersion: 2010-09-09
Description: Templete using to create new task on DMS infraestructure
Parameters:
  pDataTask:
    Description: Rules to create tast to extract data
    Type: String
  pNameTask:
    Description: Name to do unique some Stack
    Type: String
    AllowedPattern: "[a-z0-9A-Z]{2,10}"
    Default: "Task1"

Resources:

  DMSReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: full-load
      ReplicationInstanceArn:
        Fn::ImportValue: 
          pReplicationInstanceDMS-dev-sophos
      SourceEndpointArn: 
        Fn::ImportValue: 
          pEndPointSourceDMS-dev-sophos
      TableMappings: !Ref pDataTask
      TargetEndpointArn:
        Fn::ImportValue:
          pEndPointTargetDMS-dev-sophos
