AWSTemplateFormatVersion: 2010-09-09
Description: Templete using to create new task on DMS infraestructure
Parameters:
  pDMSSchemaFilter:
    Description: Schema to Stract Data
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-_%]*$
    Default: "%"
  pDMSTableFilter:
    Description: tables to Stract Data
    Type: String
    Default: "%"
    AllowedPattern: ^[a-zA-Z0-9-_%]*$

Resources:

  DMSReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: full-load
      ReplicationInstanceArn:
        Fn::ImportValue: 
          pReplicationInstanceDMS
      SourceEndpointArn: 
        Fn::ImportValue: 
          pEndPointSourceDMS
      TableMappings:
        Fn::Sub:
          - '{"rules": [{"rule-type": "selection", "rule-id": "1", "rule-action": "include", "object-locator": {"schema-name": "${schema}", "table-name": "${tables}"}, "rule-name": "1"}]}'
          - { schema: !Ref pDMSSchemaFilter, tables: !Ref pDMSTableFilter }
      TargetEndpointArn:
        Fn::ImportValue:
          pEndPointTargetDMS
